### PR TITLE
Fix/assign extnet earlier

### PR DESCRIPTION
**Pull request by garloff**
Should be merged after #106.

This one may resolve the observed trouble on wave-scs.
Currently, we do the `openstack server create JH` call immediately before assigning the FIP to the JH port; the FIP creation and assignment is preceeded by the `external-gateway-set` call for the router to ensure that the FIP can be assigned which is preceeded by a `openstack network list --external`.
If for whatever reason the `network list` or `router set --external-gateway` calls are very slow, the VM may have started to boot already before the gateway is set on the router. In the worst case, this could lead to the VM not being able to talk to the outside world via SNAT (nor via the FIP) in its early boot stage.

When we later connect to the VM, we of course have the external-gateway configured and the FIP assigned (we connect via the FIP). Nevertheless, occasioanlly, the external gateway seems to be delayed in being effective by a minute or two in such cases. This should not happen and looks like a bug to me. However, it's relatively harmless, as setting the external gateway to a router (just) after VM creation is unusual.

This fix moves the `router set --external-gateway` to happen immediately after the router creation. Thus well ahead of any VM creation. If the effectiveness of the router gateway setting is delayed enough, we might still see the bug, but I'm optimistic that this will not happen.

### CODE REVIEW

**Comment by garloff** [comment]
We have a PR review backlog on openstack-health-monitor unfortunately, so the patch was created from a branch that was branched from a branch. This tends to complicated the review, unfortunately.
Once #106 is merged, only commit #b0a1991f38c4bf09499c07a4d6c4d40a3d558b00
needs review for this one.

**Comment by garloff** [comment]
I may need to redo this branch to reconcile all the changes ...

**Comment by garloff** [comment]
I'll have to see whether I can save this branch with a few force-pushes after #106 has landed or whether I'll have to open a new clean branch with a new PR. But good comments here will of course not be lost ...

**Review by fkr — DISMISSED** [review]
LGTM

**Comment by garloff** [comment]
Sorry for the back and forth with commits!
Looking at https://github.com/SovereignCloudStack/openstack-health-monitor/pull/107/files one can see
what this change does:
* Move the assignment of external gateway to the router directly after router creation
* Error-handling: Remove router again if we don't find an external network.
  However ignore the return code from external gateway assignment. (This is for OTC, where we always have it assigned and the reassignment thus may return an error. There we'll need the enable_snat piece instead. A complete retest to see whether this still works on OTC is left for another day, though.)

**Comment by garloff** [comment]
Reviews (or re-review, @fkr) welcome!

**Review by fkr — APPROVED** [review]
LGTM

**Pull request merged**
