### PR TITLE
Feat/new collect port

### PR DESCRIPTION
**Pull request by garloff**
This is a workaround for recent openstackclient tool breakage.

### CODE REVIEW

**Comment by garloff** [comment]
Right fix might be to fix the upstream openstack client tool issue no longer reporting device_id (even if explicitly asked to).
Howerver, we need to deal with the breakage anyway, so I'd like to merge the workaround that has been in use for a while already on PCO and wave.
Also, this is needed to make #107 merge cleanly (as I built on top, needing both changes on wave).

**Comment by garloff** [comment]
Review very welcome, @osfrickler , @frosty-geek , @fkr, @nerdicbynature , @chschilling !

**Review by fkr — APPROVED** [review]
LGTM

**Comment by garloff** [comment]
Thanks for the approving review, @fkr !
Hmmm, after merging main into the branch to resolve potential conflicts, this needs re-approval for some reason.
(I have honestly no idea why this is required sometimes and sometimes not. I did not have to resolve conflicts manually, so this was not the trigger ...)

**Comment by garloff** [comment]
Oh, and then the merging is blocked vanished again, so I don't require a re-approval.
So probably just some things in github that run asynchronously ...

**Pull request merged**
